#!/bin/bash
set -e

# CarlosOS Live Build Configuration
# Configuración oficial para CarlosOS basado en Debian Bookworm
# © 2026 Carlos Torres - Todos los derechos reservados

lb config noauto \
    --architectures amd64 \
    --distribution bookworm \
    --debian-installer live \
    --mode debian \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap http://httpredir.debian.org/debian \
    --mirror-chroot http://httpredir.debian.org/debian \
    --mirror-binary http://httpredir.debian.org/debian \
    --mirror-chroot-security http://security.debian.org/debian-security \
    --mirror-binary-security http://security.debian.org/debian-security \
    --parent-mirror-bootstrap http://httpredir.debian.org/debian \
    --parent-mirror-chroot http://httpredir.debian.org/debian \
    --parent-mirror-binary http://httpredir.debian.org/debian \
    --apt-options "--yes" \
    --bootappend-live "boot=live components username=user hostname=carlosos quiet splash" \
    --iso-application "CarlosOS Live 1.0" \
    --iso-publisher "Carlos Torres" \
    --iso-volume "CARLOSOS_LIVE" \
    --iso-preparer "Carlos Torres Project" \
    --binary-images iso-hybrid \
    --security false \
    --memtest none \
    --firmware-chroot true
